version: '3'
services:

  # Spring Service
  app:
    container_name: cameinw-app
    build:
      context: ./cameinw-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - SERVICE_NAME=${SPRING_SERVICE_NAME}
      - SERVICE_TAGS=${SPRING_SERVICE_TAGS}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
    tty: true
    volumes:
      - ./cameinw-backend/certs:/app/certs
    depends_on:
      - db
    networks:
      - cameinw-net
    restart: on-failure

  # MySQL Service
  db:
    image: mysql:latest
    container_name: cameinw-db
    volumes:
      - ./mysql/dbdata/:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "4306:3306"
    env_file:
      - .env
    environment:
      - SERVICE_TAGS=${MYSQL_SERVICE_TAGS}
      - SERVICE_NAME=${MYSQL_SERVICE_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - cameinw-net


  # PHPMyAdmin Service
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: cameinw-phpMyAdmin
    ports:
      - "8085:80"
    links:
      - db
    restart: unless-stopped
    networks:
      - cameinw-net


#Docker Networks
networks:
  cameinw-net:
    driver: bridge
