version: '3.1'

services:

  #Spring Service
  cameinw-backend:
    image: cameinw-backend
    build:
      context: ./cameinw-backend
      dockerfile: ./cameinw.Dockerfile
    container_name: cameinw-app
    tty: true
    depends_on:
      - cameinw-db
    ports:
      - 8090:8080
    environment:
      MYSQL_HOST: cameinw-db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PORT: 3306
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
    stdin_open: true
    networks:
      - cameinw-net
    restart: on-failure

  # MySQL Service
  cameinw-db:
    image: mysql:latest
    container_name: cameinw-db
    command: --skip-host-cache --skip-name-resolve
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 20s
      timeout: 10s
      retries: 5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cameinw_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - cameinw-net
    restart: unless-stopped

#Docker Networks
networks:
  cameinw-net:
    driver: bridge